# Generated by Django 4.2.6 on 2025-05-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=1440),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tariff',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
