# Generated by Django 4.2.6 on 2025-06-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tariffs', '0002_tariff_duration_minutes_tariff_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
