# Generated by Django 5.1.1 on 2024-10-11 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(choices=[('daily', 'Дневной'), ('monthly', 'Месячный')], max_length=50),
        ),
    ]
