# Generated by Django 5.1.1 on 2024-10-11 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_payment_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
