# Generated by Django 4.2.6 on 2024-11-24 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_tariff_created_at_tariff_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tariff',
            name='is_deleted',
        ),
    ]
