# Generated by Django 4.2.6 on 2024-11-27 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_tariff_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingspot',
            name='spot_number',
            field=models.IntegerField(unique=True),
        ),
    ]
