# Generated by Django 5.1.1 on 2024-10-13 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
