# Generated by Django 4.2.6 on 2024-10-13 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_booking_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tariff',
            name='name',
            field=models.CharField(choices=[('daily', 'Дневной'), ('monthly', 'Месячный')], max_length=50, unique=True),
        ),
    ]
