# Generated by Django 4.2.6 on 2024-12-01 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_customuser_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingspot',
            name='id',
        ),
        migrations.AlterField(
            model_name='parkingspot',
            name='spot_number',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
