# Generated by Django 4.2.6 on 2025-04-28 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_data', models.TextField()),
                ('access_granted', models.BooleanField()),
                ('failure_reason', models.CharField(choices=[('booking_not_found', 'Бронирование не найдено'), ('booking_unpaid', 'Бронирование не оплачено'), ('invalid_signature', 'Подпись не совпадает')], max_length=50, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_logs', to='bookings.booking')),
            ],
        ),
    ]
