# Generated by Django 4.2.6 on 2025-04-26 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_license_plate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='license_plate',
            field=models.CharField(max_length=15),
        ),
        migrations.AddConstraint(
            model_name='car',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('license_plate',), name='unique_license_plate_active'),
        ),
    ]
