# Generated by Django 4.2.6 on 2025-04-16 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParkingSpot',
            fields=[
                ('spot_number', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('booked', 'забронировано'), ('available', 'свободно'), ('unavailable', 'недоступно для бронирования')], max_length=50)),
            ],
        ),
    ]
