# Generated by Django 4.2.6 on 2025-04-16 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_remove_payment_booking_delete_booking_delete_payment'),
        ('cars', '0001_initial'),
        ('tariffs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Активное'), ('completed', 'Завершено'), ('cancelled', 'Отменено')], default='active', max_length=20)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='cars.car')),
                ('parking_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='api.parkingspot')),
                ('tariff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='tariffs.tariff')),
            ],
        ),
    ]
